/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface AuditLogInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizedWriters"
      | "logAction"
      | "logs"
      | "owner"
      | "setAuthorizedWriter"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ComplianceActionLogged" | "WriterUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizedWriters",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logAction",
    values: [BytesLike, string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "logs", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedWriter",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizedWriters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "logAction", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedWriter",
    data: BytesLike
  ): Result;
}

export namespace ComplianceActionLoggedEvent {
  export type InputTuple = [
    logId: BytesLike,
    entityId: BytesLike,
    actionType: string,
    dataHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    logId: string,
    entityId: string,
    actionType: string,
    dataHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    logId: string;
    entityId: string;
    actionType: string;
    dataHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WriterUpdatedEvent {
  export type InputTuple = [writer: AddressLike, isActive: boolean];
  export type OutputTuple = [writer: string, isActive: boolean];
  export interface OutputObject {
    writer: string;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AuditLog extends BaseContract {
  connect(runner?: ContractRunner | null): AuditLog;
  waitForDeployment(): Promise<this>;

  interface: AuditLogInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizedWriters: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  logAction: TypedContractMethod<
    [_entityId: BytesLike, _actionType: string, _dataHash: BytesLike],
    [string],
    "nonpayable"
  >;

  logs: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, string] & {
        entityId: string;
        actionType: string;
        dataHash: string;
        timestamp: bigint;
        storedBy: string;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  setAuthorizedWriter: TypedContractMethod<
    [_writer: AddressLike, _isActive: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizedWriters"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "logAction"
  ): TypedContractMethod<
    [_entityId: BytesLike, _actionType: string, _dataHash: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "logs"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, string] & {
        entityId: string;
        actionType: string;
        dataHash: string;
        timestamp: bigint;
        storedBy: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAuthorizedWriter"
  ): TypedContractMethod<
    [_writer: AddressLike, _isActive: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ComplianceActionLogged"
  ): TypedContractEvent<
    ComplianceActionLoggedEvent.InputTuple,
    ComplianceActionLoggedEvent.OutputTuple,
    ComplianceActionLoggedEvent.OutputObject
  >;
  getEvent(
    key: "WriterUpdated"
  ): TypedContractEvent<
    WriterUpdatedEvent.InputTuple,
    WriterUpdatedEvent.OutputTuple,
    WriterUpdatedEvent.OutputObject
  >;

  filters: {
    "ComplianceActionLogged(bytes32,bytes32,string,bytes32,uint256)": TypedContractEvent<
      ComplianceActionLoggedEvent.InputTuple,
      ComplianceActionLoggedEvent.OutputTuple,
      ComplianceActionLoggedEvent.OutputObject
    >;
    ComplianceActionLogged: TypedContractEvent<
      ComplianceActionLoggedEvent.InputTuple,
      ComplianceActionLoggedEvent.OutputTuple,
      ComplianceActionLoggedEvent.OutputObject
    >;

    "WriterUpdated(address,bool)": TypedContractEvent<
      WriterUpdatedEvent.InputTuple,
      WriterUpdatedEvent.OutputTuple,
      WriterUpdatedEvent.OutputObject
    >;
    WriterUpdated: TypedContractEvent<
      WriterUpdatedEvent.InputTuple,
      WriterUpdatedEvent.OutputTuple,
      WriterUpdatedEvent.OutputObject
    >;
  };
}
