/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ComplianceGuardianInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "auditLog"
      | "evaluateTransaction"
      | "freezeAgent"
      | "frozenWallets"
      | "owner"
      | "whitelist"
      | "whitelistAgent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentFrozen"
      | "AgentWhitelisted"
      | "TransactionEvaluated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "auditLog", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "evaluateTransaction",
    values: [string, AddressLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "freezeAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "frozenWallets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "whitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistAgent",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "auditLog", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "evaluateTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "freezeAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "frozenWallets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "whitelist", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "whitelistAgent",
    data: BytesLike
  ): Result;
}

export namespace AgentFrozenEvent {
  export type InputTuple = [agent: AddressLike];
  export type OutputTuple = [agent: string];
  export interface OutputObject {
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentWhitelistedEvent {
  export type InputTuple = [agent: AddressLike];
  export type OutputTuple = [agent: string];
  export interface OutputObject {
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionEvaluatedEvent {
  export type InputTuple = [txId: string, approved: boolean, reason: string];
  export type OutputTuple = [txId: string, approved: boolean, reason: string];
  export interface OutputObject {
    txId: string;
    approved: boolean;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ComplianceGuardian extends BaseContract {
  connect(runner?: ContractRunner | null): ComplianceGuardian;
  waitForDeployment(): Promise<this>;

  interface: ComplianceGuardianInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  auditLog: TypedContractMethod<[], [string], "view">;

  evaluateTransaction: TypedContractMethod<
    [
      txId: string,
      agent: AddressLike,
      amount: BigNumberish,
      isRiskHigh: boolean
    ],
    [boolean],
    "nonpayable"
  >;

  freezeAgent: TypedContractMethod<[_agent: AddressLike], [void], "nonpayable">;

  frozenWallets: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  whitelist: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  whitelistAgent: TypedContractMethod<
    [_agent: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "auditLog"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "evaluateTransaction"
  ): TypedContractMethod<
    [
      txId: string,
      agent: AddressLike,
      amount: BigNumberish,
      isRiskHigh: boolean
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "freezeAgent"
  ): TypedContractMethod<[_agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "frozenWallets"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "whitelist"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "whitelistAgent"
  ): TypedContractMethod<[_agent: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AgentFrozen"
  ): TypedContractEvent<
    AgentFrozenEvent.InputTuple,
    AgentFrozenEvent.OutputTuple,
    AgentFrozenEvent.OutputObject
  >;
  getEvent(
    key: "AgentWhitelisted"
  ): TypedContractEvent<
    AgentWhitelistedEvent.InputTuple,
    AgentWhitelistedEvent.OutputTuple,
    AgentWhitelistedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionEvaluated"
  ): TypedContractEvent<
    TransactionEvaluatedEvent.InputTuple,
    TransactionEvaluatedEvent.OutputTuple,
    TransactionEvaluatedEvent.OutputObject
  >;

  filters: {
    "AgentFrozen(address)": TypedContractEvent<
      AgentFrozenEvent.InputTuple,
      AgentFrozenEvent.OutputTuple,
      AgentFrozenEvent.OutputObject
    >;
    AgentFrozen: TypedContractEvent<
      AgentFrozenEvent.InputTuple,
      AgentFrozenEvent.OutputTuple,
      AgentFrozenEvent.OutputObject
    >;

    "AgentWhitelisted(address)": TypedContractEvent<
      AgentWhitelistedEvent.InputTuple,
      AgentWhitelistedEvent.OutputTuple,
      AgentWhitelistedEvent.OutputObject
    >;
    AgentWhitelisted: TypedContractEvent<
      AgentWhitelistedEvent.InputTuple,
      AgentWhitelistedEvent.OutputTuple,
      AgentWhitelistedEvent.OutputObject
    >;

    "TransactionEvaluated(string,bool,string)": TypedContractEvent<
      TransactionEvaluatedEvent.InputTuple,
      TransactionEvaluatedEvent.OutputTuple,
      TransactionEvaluatedEvent.OutputObject
    >;
    TransactionEvaluated: TypedContractEvent<
      TransactionEvaluatedEvent.InputTuple,
      TransactionEvaluatedEvent.OutputTuple,
      TransactionEvaluatedEvent.OutputObject
    >;
  };
}
