/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAuditLog,
  IAuditLogInterface,
} from "../../ComplianceGuardian.sol/IAuditLog";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "entityId",
        type: "string",
      },
      {
        internalType: "string",
        name: "actionType",
        type: "string",
      },
      {
        internalType: "string",
        name: "ipfsHash",
        type: "string",
      },
    ],
    name: "logAction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAuditLog__factory {
  static readonly abi = _abi;
  static createInterface(): IAuditLogInterface {
    return new Interface(_abi) as IAuditLogInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IAuditLog {
    return new Contract(address, _abi, runner) as unknown as IAuditLog;
  }
}
